/* Editorial review is authored, never inferred or generated by this read-only check. */
'use strict';
const fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'../..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const plain=s=>s.replace(/<[^>]*>/g,'').replace(/&amp;/g,'&').replace(/\s+/g,' ').trim();
const fail=m=>{throw Error('L&L notebook: '+m+'; review notebook/index.html and notebook/reviews.json before completing publication.');};
const unique=a=>Array.isArray(a)&&a.every(x=>typeof x==='string')&&new Set(a).size===a.length;
const validDate=d=>typeof d==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(d)&&Number.isFinite(Date.parse(d))&&new Date(d).toISOString().slice(0,10)===d;
function validate(input={}){
 const journal=input.journal??read('weekly-economics-environment/index.html');
 const notebook=input.notebook??read('weekly-economics-environment/notebook/index.html');
 const reviews=input.reviews??JSON.parse(read('weekly-economics-environment/notebook/reviews.json'));
 const main=journal.match(/<main[^>]*id="edition"[^>]*>([\s\S]*?)<\/main>/)?.[1];
 if(!main)fail('canonical edition archive is missing');
 const editions=[...main.matchAll(/<section class="edition"[^>]*data-edition="([^"]+)"[^>]*>([\s\S]*?)(?=<section class="edition"|$)/g)];
 if(!editions.length||new Set(editions.map(e=>e[1])).size!==editions.length)fail('edition dates are missing or duplicated');
 const targets=new Map(),dates=editions.map(e=>e[1]).sort();
 for(const e of editions){
  if(!validDate(e[1]))fail('invalid edition date '+e[1]);
  for(const m of e[0].matchAll(/\bid="([^"]+)"/g))targets.set(m[1],e[1]);
 }
 const concepts=new Map();
 for(const m of notebook.matchAll(/<article class="concept" id="([^"]+)"[\s\S]*?<\/article>/g)){
  if(concepts.has(m[1]))fail('duplicate concept '+m[1]);
  const html=m[0],seen=html.match(/<div class="seen">([\s\S]*?)<\/div>/)?.[1];
  if(!/<p class="canonical">[\s\S]+?<\/p>/.test(html)||!/<h3>Why it matters<\/h3><p>[\s\S]+?<\/p>/.test(html)||!/<h3>A caution<\/h3><p>[\s\S]+?<\/p>/.test(html)||!seen)fail('incomplete concept '+m[1]);
  const links=[...seen.matchAll(/href="\.\.\/#([^"]+)"/g)].map(x=>x[1]);
  if(!links.length||new Set(links).size!==links.length)fail('missing or duplicate references in '+m[1]);
  for(const id of links)if(!targets.has(id))fail('unresolved journal reference #'+id+' in '+m[1]);
  const referenced=links.map(id=>targets.get(id)).sort(),last=referenced.at(-1);
  const stamp=new Date(last+'T12:00:00Z').toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'});
  if(!seen.includes('<span>Last revisited · '+stamp+'</span>'))fail('Last revisited must match actual references in '+m[1]);
  concepts.set(m[1],{dates:new Set(referenced),first:referenced[0]});
 }
 if(!concepts.size)fail('no cumulative concepts');
 const index=notebook.match(/<nav class="concept-index"[^>]*>([\s\S]*?)<\/nav>/)?.[1]||'';
 const indexed=[...index.matchAll(/href="#([^"]+)"/g)].map(x=>x[1]);
 if(!unique(indexed)||indexed.length!==concepts.size||indexed.some(id=>!concepts.has(id)))fail('concept index and permanent entries disagree');
 if(reviews.version!==1||!reviews.reviews||typeof reviews.reviews!=='object')fail('invalid review registry');
 for(const date of Object.keys(reviews.reviews))if(!dates.includes(date))fail('review has no published edition '+date);
 for(const e of editions){
  const date=e[1],review=reviews.reviews[date];
  if(!review)fail('missing documented review for '+date);
  if(!validDate(review.reviewedOn)||review.reviewedOn<date)fail('invalid review date for '+date);
  const readings=[...e[0].matchAll(/<article class="entry"[^>]*id="([^"]+)"/g)].map(x=>x[1]);
  const synthesis=e[0].match(/<section class="synthesis"[^>]*id="([^"]+)"/)?.[1];
  if(readings.length!==5||!unique(review.readings)||JSON.stringify([...review.readings].sort())!==JSON.stringify(readings.sort())||review.synthesis!==synthesis)fail('review must cover all five readings and synthesis for '+date);
  if(!unique(review.revisited)||!unique(review.added)||!unique([...review.revisited,...review.added])||typeof review.note!=='string'||review.note.trim().length<20)fail('document editorial decisions, including a reason when no additions are justified, for '+date);
  for(const id of [...review.revisited,...review.added])if(!concepts.get(id)?.dates.has(date))fail('reviewed concept '+id+' lacks a reference to '+date);
  for(const id of review.added)if(concepts.get(id).first!==date)fail('new concept '+id+' already belongs to an earlier edition');
 }
 return {editions:editions.length,concepts:concepts.size,newestReviewed:dates.at(-1)};
}
module.exports={validate};
if(require.main===module){try{console.log(JSON.stringify(validate()));}catch(e){console.error(e.message);process.exitCode=1;}}
