const fs=require('fs'),vm=require('vm'),assert=require('assert');
const source=fs.readFileSync('weekly-economics-environment/index.html','utf8');
const block=source.slice(source.indexOf('function heronScroll()'),source.indexOf('function initCompanion()'));
let on=true,settled=0;const dismissed=new Set();
const ctx={companionMobile:()=>true,companionOn:()=>on,settleHeron:()=>settled++,addTo:(key,id)=>dismissed.add(id),HERON:{closed:{},items:[],current:null,edition:{dataset:{edition:'test'}}}};
vm.createContext(ctx);vm.runInContext(block,ctx);
function item(id){const classes=new Set();return {a:{id},state:'perched',btn:{hidden:false,classList:{add:k=>classes.add(k),remove:k=>classes.delete(k),contains:k=>classes.has(k)},setAttribute(k,v){this[k]=v}},panel:{hidden:false}}}
const a=item('a'),b=item('b');ctx.HERON.items=[a,b];
ctx.summon(a);assert.equal(a.state,'note');assert.equal(ctx.HERON.current,a);
ctx.release(a);assert(!a.btn.hidden&&a.panel.hidden,'Close collapses contents but retains the label');assert(a.btn.classList.contains('vacant'),'Close hides the bird');assert.equal(a.btn['aria-expanded'],'false');assert(ctx.HERON.closed['test:a']);assert.equal(ctx.HERON.current,null);assert(!b.btn.hidden,'closing affects only this perch');
ctx.summon(a);assert.equal(a.state,'note','retained label can reopen');assert(!a.btn.hidden);assert(!a.btn.classList.contains('vacant'),'reopening uses the existing inspection pose without flight');
ctx.dismissHeron(a);assert(a.btn.hidden&&a.panel.hidden,'dismissal hides both bird and label');assert(dismissed.has('a'),'dismissal is persisted');ctx.summon(a);assert(a.btn.hidden,'dismissed intervention cannot reopen');
ctx.summon(b);assert.equal(b.state,'note');on=false;ctx.release(b);const c=item('c');ctx.summon(c);assert.equal(c.state,'perched','Heron Off prevents opening');ctx.heronTick();assert.equal(settled,1);on=true;ctx.companionMobile=()=>false;ctx.summon(c);assert.equal(c.state,'perched','desktop cannot open a companion');
assert(!source.includes('new IntersectionObserver(function(ents)'),'standing perches do not depend on scroll-triggered arrival');
assert(source.includes("it.btn.hidden=!companionMobile()||!companionOn()||it.state==='dismissed'"));
assert(!source.includes('.heron-perch:hover .pose-inspect'),'hover alone must not bend the standing bird');
console.log('Heron lifecycle: open → close → bird gone + label retained → reopen; persistent dismissal; independent items, mobile scope and Off passed.');

// The actual open/close handler retains contents, labels and keyboard focus semantics.
const uiItem=item('ui');let focusReturns=0,scrollReturns=0;
uiItem.btn.focus=()=>focusReturns++;uiItem.btn.scrollIntoView=()=>scrollReturns++;uiItem.panel.focus=()=>{};
const ui={companionMobile:()=>true,companionOn:()=>true,settleHeron(){},addTo(){},HERON:{closed:{},current:null,edition:{dataset:{edition:'test'}}},slot:{},itemOf:()=>uiItem,panel:uiItem.panel,btn:uiItem.btn,art:{},a:uiItem.a,seenKey:'seen',HV:{mark(){}}};
vm.createContext(ui);vm.runInContext(block,ui);
vm.runInContext(source.slice(source.indexOf('function openP(o,quiet)'),source.indexOf("var go=panel.querySelector('.hv-goto')")),ui);
ui.openP(true);assert(!uiItem.panel.hidden);ui.openP(false);assert(uiItem.panel.hidden&&!uiItem.btn.hidden);assert.equal(focusReturns,1);
ui.openP(true);assert(!uiItem.panel.hidden,'the retained label reopens full contents');ui.slot.closeHeronNote();assert(uiItem.panel.hidden&&!uiItem.btn.hidden);assert.equal(focusReturns,1,'automatic close must not steal focus from the newly opened note');assert.equal(scrollReturns,1,'automatic close must not scroll back to the previous label');
console.log('Heron DOM handler: contents reopen, direct Close restores focus, automatic close preserves the new reading position passed.');

// Exercise the real shelf controller with geometry and node identity, including resize restoration.
const shelfSource=fs.readFileSync('personal-updates/mobile-shelf.js','utf8');
const shelfEvents={},media={matches:true,addEventListener:(name,fn)=>media.change=fn},frames=[];
let panelNode;
function container(){return {children:[],dataset:{},hidden:false,setAttribute(){},append(node){if(node.parent)node.parent.children.splice(node.parent.children.indexOf(node),1);this.children.push(node);node.parent=this}}}
const notes=[0,1,2].map(i=>({hidden:false,liveTitle:'title-'+i}));
const units=notes.map((note,i)=>{const unit=container();unit.append(note);unit.querySelector=s=>s==='.press-note'?note:{dataset:{issueMark:['fb','sp','cp'][i]}};unit.getBoundingClientRect=()=>({left:16+i*324-shelf.scrollLeft});return unit});
const shelf={scrollLeft:0,querySelectorAll:()=>units,getBoundingClientRect:()=>({left:16}),after:node=>panelNode=node,addEventListener:(name,fn)=>shelfEvents[name]=fn,scrollTo:o=>shelf.scrollLeft=o.left};
const shelfContext={document:{getElementById:()=>shelf,createElement:container,fonts:{ready:{then(){}}}},matchMedia:()=>media,requestAnimationFrame:fn=>{frames.push(fn);return frames.length},ResizeObserver:class{observe(){}},addEventListener(){}};
vm.createContext(shelfContext);vm.runInContext(shelfSource,shelfContext);
assert.equal(panelNode.dataset.publication,'fb');assert.equal(panelNode.children.length,3);assert(units.every(u=>u.children.length===0),'mobile shelf holds only covers');
for(const [index,key] of ['fb','sp','cp'].entries()){shelf.scrollLeft=index*324;shelfEvents.scrollend();assert.equal(panelNode.dataset.publication,key);assert.deepEqual(notes.map(n=>n.hidden),notes.map((n,i)=>i!==index));assert.equal(panelNode.children[index],notes[index],'live hooks retain their original node');}
notes[2].liveTitle='new live title';assert.equal(panelNode.children[2].liveTitle,'new live title','live updates cannot leave a stale clone');
media.matches=false;media.change();assert(panelNode.hidden);assert(units.every((u,i)=>u.children[0]===notes[i]&&!notes[i].hidden),'desktop gets its exact original notes back');
media.matches=true;media.change();assert.equal(panelNode.dataset.publication,'cp');shelfEvents.focusin({target:{closest:()=>units[0]}});assert.equal(panelNode.dataset.publication,'fb','keyboard focus keeps the panel synchronized');
console.log('Mobile shelf: cover-only browsing, synchronized stationary notes, original live hooks, keyboard selection and desktop restoration passed.');

const mobile=fs.readFileSync('personal-updates/mobile/mobile.js','utf8');
const recoveryBlock=mobile.slice(mobile.indexOf('const workbook='),mobile.indexOf("addEventListener('periodicals:edition'"));
function recoveryContext(path){
 const stored=new Map(),els=[{id:'article-one',top:800,height:1200,title:'First substantial article'},{id:'connections',top:2000,height:1000,title:'What connects this week'}].map(e=>({...e,offsetHeight:e.height,getClientRects:()=>[1],getBoundingClientRect(){return {top:this.top-c.scrollY,bottom:this.top+this.height-c.scrollY}},querySelector:()=>({textContent:e.title})}));
 const resume={isConnected:true,hidden:true},c={path,stored,state:null,pending:null,saved:null,timer:null,engaged:false,location:{hash:''},scrollY:0,innerHeight:852,resume,resumeTitle:{},resumeContext:{},prev:{},next:{},clearTimeout(){},requestAnimationFrame:f=>f(),images(){},read:k=>stored.get(k)||null,write:(k,v)=>stored.set(k,v),localStorage:{removeItem:k=>stored.delete(k)},window:{scrollTo:(p,y)=>{c.scrollY=typeof p==='number'?y:p.top}},document:{addEventListener(){},readyState:'complete',documentElement:{scrollHeight:3200},body:{classList:{contains:()=>false}},getElementById:id=>els.find(e=>e.id===id),querySelector:()=>null,querySelectorAll:s=>s.includes('.ix-item')?[]:els}};
 vm.createContext(c);vm.runInContext(recoveryBlock,c);return c;
}
const reader=recoveryContext('/weekly-economics-environment/');reader.state={current:'2026-09-25',dates:['2026-09-25'],title:'A resilient economy',hash:d=>'#edition-'+d};reader.scrollY=220;reader.save();assert(!reader.read(reader.key()),'masthead scrolling does not create Resume');reader.scrollY=900;reader.save();let record=reader.read(reader.key());assert.equal(record.section,'article-one');assert.equal(record.offset,220);assert(record.label.includes('First substantial article'));reader.pending=record;reader.location.hash=reader.state.hash(record.edition);reader.scrollY=0;reader.restore();assert.equal(reader.scrollY,900,'semantic section and local offset restore reading position');reader.scrollY=2700;reader.save();assert(!reader.read(reader.key()),'Resume is removed near end');
const brief=recoveryContext('/daily-watchlist-5/');brief.state={current:'2026-09-30',label:'30 September',dates:['2026-09-30'],hash:d=>'#'+d};brief.scrollY=1200;brief.save();assert(brief.read(brief.key()).label.includes('Story article-one')); // story labels are derived from stable story IDs.
const book=recoveryContext('/daily-econ-challenge/');book.state={current:'2026-09-30',dates:['2026-09-30'],progress:{no:3,question:3,answered:2,total:8,submitted:false}};book.save();assert.equal(book.read(book.key()).question,3);assert.equal(book.read(book.key()).label,'No. 003 · Question 4 of 8');book.state.hash=d=>'#'+d;book.location.hash=book.state.hash(book.state.current);let restored;book.state.resume=q=>{restored=q};book.pending=book.read(book.key());book.restore();assert.equal(restored,3);book.state.progress.submitted=true;book.save();assert(!book.read(book.key()),'submitted sets do not offer Resume');
console.log('Resume: masthead threshold, semantic section/offset, near-end suppression, story context, native question recovery and completed-set suppression passed.');

const recovering=recoveryContext('/daily-econ-challenge/');const detail={current:'2026-09-30',dates:['2026-09-30'],hash:d=>'#'+d,progress:{no:3,question:1,answered:1,total:8,submitted:false},recovery:{edition:'2026-09-30',question:1,label:'No. 003 · Question 2 of 8'}};recovering.update({detail});assert(!recovering.resume.hidden);recovering.update({detail:{...detail,progress:{...detail.progress,question:2}}});assert(recovering.resume.hidden);recovering.update({detail:{...detail,progress:{...detail.progress,question:2}}});assert(recovering.resume.hidden,'rendering an active question must not reoffer recovery');console.log('Active-session Resume suppression passed.');

const swipeBlock=mobile.slice(mobile.indexOf('let touch=null;'),mobile.indexOf('function theme()'));
const listeners={},swipes=[];let touchTime=0;
const gesture={state:{},tools:{addEventListener:(n,f)=>{listeners[n]=f}},turn:d=>swipes.push(d),Date:{now:()=>touchTime}};
vm.createContext(gesture);vm.runInContext(swipeBlock,gesture);
function swipe(dx,dy,elapsed){touchTime=0;listeners.touchstart({touches:[{clientX:200,clientY:800}]});touchTime=elapsed;listeners.touchend({changedTouches:[{clientX:200+dx,clientY:800+dy}]})}
swipe(120,5,200);swipe(-120,5,200);swipe(20,2,200);swipe(120,100,200);swipe(120,5,900);listeners.touchstart({touches:[{clientX:0,clientY:0}]});listeners.touchcancel();listeners.touchend({changedTouches:[{clientX:120,clientY:0}]});assert.deepEqual(swipes,[-1,1]);assert.deepEqual(Object.keys(listeners),['touchstart','touchend','touchcancel']);console.log('Control-bar swipe direction, movement/time thresholds, vertical rejection and cancellation passed.');

book.state.progress.submitted=false;book.state.progress.answered=8;book.write(book.key(),{edition:'2026-09-30',question:7});book.save();assert(!book.read(book.key()),'fully answered but unsubmitted sets are also at the end');reader.scrollY=1000;reader.pending={edition:reader.state.current,fromTop:true};reader.restore();assert.equal(reader.scrollY,0);console.log('Start-from-top semantic recovery and fully answered set suppression passed.');

// A real transition must remain guarded while font layout / animation frames are pending.
const reset=recoveryContext('/daily-watchlist-5/'),resetFrames=[],fontReady=[];
reset.state={current:'2026-10-01',dates:['2026-10-01'],label:'Oct 1',hash:d=>'#'+d};reset.location.hash='#2026-10-01';
reset.document.querySelectorAll('.story')[0].id='story-03';reset.scrollY=1100;reset.save();assert.equal(reset.read(reset.key()).section,'story-03');
reset.localStorage.removeItem(reset.key());reset.pending={edition:'2026-10-01',fromTop:true};reset.requestAnimationFrame=f=>resetFrames.push(f);reset.document.fonts={ready:{then:f=>fontReady.push(f)}};
reset.restore();reset.restore();reset.save();assert.equal(fontReady.length,1,'reentrant renders must not schedule a second restoration');assert(!reset.read(reset.key()),'clearing progress must survive an old-position save during transition');assert(reset.pending,'saving stays suspended until the scroll is applied');
fontReady.shift()();resetFrames.shift()();reset.save();assert(!reset.read(reset.key()));resetFrames.shift()();assert.equal(reset.scrollY,0);assert.equal(reset.pending,null);reset.save();assert(!reset.read(reset.key()),'the discarded Story 03 offset cannot return at the top');

const cancelled=recoveryContext('/daily-watchlist-5/'),cancelFrames=[];cancelled.state=reset.state;cancelled.location.hash='#2026-10-01';cancelled.scrollY=1100;cancelled.pending={edition:'2026-10-01',fromTop:true};cancelled.requestAnimationFrame=f=>cancelFrames.push(f);cancelled.restore();cancelled.location.hash='#2026-10-01/04';cancelFrames.shift()();cancelFrames.shift()();assert.equal(cancelled.scrollY,1100,'a later explicit story route cancels the stale top reset');assert.equal(cancelled.pending,null);

// Reusing an existing edition hash may not announce a new edition: hashchange must complete Resume.
const hashStart=mobile.indexOf("addEventListener('hashchange',()=>"),hashEnd=mobile.indexOf("\naddEventListener('scroll'",hashStart);
let onHash;const reused=recoveryContext('/weekly-economics-environment/');reused.state={current:'2026-09-25',dates:['2026-09-25'],hash:d=>'#edition-'+d};reused.location.hash='#edition-2026-09-25';reused.pending={edition:'2026-09-25',section:'article-one',offset:220};reused.addEventListener=(name,fn)=>{onHash=fn};vm.runInContext(mobile.slice(hashStart,hashEnd),reused);onHash();assert.equal(reused.scrollY,900,'same-edition Resume restores the saved entry without a new announcement');
reused.pending={edition:'2026-09-25',fromTop:true};let fullMode=false,heroScroll=false;reused.state.full=()=>{fullMode=true};reused.document.querySelector=()=>({scrollIntoView:o=>{assert.equal(o.block,'start');heroScroll=true}});reused.restore();assert(fullMode&&heroScroll,'L&L Start from top restores Full Edition and its beginning');

const resetBook=recoveryContext('/daily-econ-challenge/');resetBook.location.hash='#2026-10-01';resetBook.state={current:'2026-10-01',dates:['2026-10-01'],hash:d=>'#'+d,progress:{no:4,question:3,answered:2,total:8,submitted:false},start(){resetBook.update({detail:{...resetBook.state,progress:{...resetBook.state.progress,question:0}}})}};resetBook.scrollY=900;resetBook.pending={edition:'2026-10-01',fromTop:true};resetBook.restore();assert.equal(resetBook.state.progress.question,0);assert.equal(resetBook.scrollY,0);assert(!resetBook.read(resetBook.key()),'the old question must not be saved by a reentrant render');
console.log('Deterministic transition guard, cancelled route, same-edition hash completion, Story 03 top reset, L&L full/hero reset and Workbook question reset passed.');

// Commonplace owns delayed generated-source anchors; ordinary edition/article routing stays page-owned.
const cpSource=fs.readFileSync('personal-updates/commonplace/commonplace.js','utf8'),reveal=cpSource.slice(cpSource.indexOf('function revealHash()'),cpSource.indexOf('function scanFB()'));
const cpFrames=[],cpScroll=[],cpContext={location:{hash:'#edition-2026-09-25'},requestAnimationFrame:f=>cpFrames.push(f),document:{getElementById:id=>({scrollIntoView:o=>cpScroll.push(id)})}};vm.createContext(cpContext);vm.runInContext(reveal,cpContext);cpContext.revealHash();assert.equal(cpFrames.length,0,'Commonplace cannot recenter an entire edition');cpContext.location.hash='#cp-ll-2026-09-25-figure-1';cpContext.revealHash();cpContext.location.hash='#edition-2026-09-25';cpFrames.shift()();assert.equal(cpScroll.length,0,'a stale source anchor cannot override Start from top');cpContext.location.hash='#cp-ll-2026-09-25-figure-1';cpContext.revealHash();cpFrames.shift()();assert.equal(cpScroll.length,1);

const navigationPages=['personal-updates/index.html','daily-watchlist-5/index.html','weekly-economics-environment/index.html','daily-econ-challenge/index.html','personal-updates/commonplace/index.html','personal-updates/handbook/index.html','weekly-economics-environment/notebook/index.html'];
for(const path of navigationPages){const source=fs.readFileSync(path,'utf8'),html=source.replace(/<script\b[^>]*>[\s\S]*?<\/script>/g,''),ids=new Set([...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]));for(const [,hash]of html.matchAll(/<a\b[^>]*\bhref="(#.*?)"/g)){if(ids.has(hash.slice(1)))continue;if(hash==='#'&&/id="(?:latestLink|homeLink)"/.test(html))continue;if(path==='weekly-economics-environment/index.html'&&hash==='#field-register'){assert(source.includes("if(location.hash==='#field-register'){openRegister();return}"));continue}if(path==='daily-econ-challenge/index.html'&&(hash==='#archive'||hash==='#bench')){assert(source.includes(hash==='#archive'?"if(h!=='archive')":'id="bench"'));continue}assert.fail(path+' has an unhandled static anchor '+hash)}}
console.log('Static navigation targets on all principal Periodicals pages and the notebook; generated Commonplace anchors and stale-hash cancellation passed.');

// Exercise publication-owned routes without substituting a generic DOM anchor for synthetic hashes.
const fbPage=fs.readFileSync('daily-watchlist-5/index.html','utf8'),fbRoute=fbPage.slice(fbPage.indexOf('function load(){'),fbPage.indexOf("document.getElementById('latestLink').addEventListener"));
const routedBrief=[],fbRouter={location:{hash:'#2026-10-01/03'},mount:{firstElementChild:{}},data:{editions:[{date:'2026-10-01'},{date:'2026-10-02'}]},ordered:[{date:'2026-10-01'},{date:'2026-10-02'}],render:(ed,story)=>routedBrief.push([ed.date,story])};vm.createContext(fbRouter);vm.runInContext(fbRoute,fbRouter);fbRouter.load();assert.deepEqual(routedBrief.at(-1),['2026-10-01','03']);fbRouter.location.hash='#briefing';fbRouter.load();assert.equal(routedBrief.length,1,'native skip does not replace an existing older edition');fbRouter.location.hash='#2026-10-01';fbRouter.load();assert.deepEqual(routedBrief.at(-1),['2026-10-01',undefined],'edition-only route discards a story anchor');
const wbPage=fs.readFileSync('daily-econ-challenge/index.html','utf8'),wbRoute=wbPage.slice(wbPage.indexOf('function route(){'),wbPage.indexOf("document.getElementById('homeLink').addEventListener"));
const wbRoutes=[],wbTimers=[],wbTargets=[],oldSet={date:'2026-10-01',questions:[{id:'q1'},{id:'q4'}]},latestSet={date:'2026-10-02',questions:[{id:'q1'}]},wbRouter={location:{hash:'#2026-10-01/q4'},EDITIONS:[latestSet,oldSet],ed:null,st:null,load:()=>null,fresh:()=>({current:0,answers:{},submitted:false}),render:()=>wbRoutes.push(wbRouter.ed.date),window:{scrollTo(){}},setTimeout:f=>wbTimers.push(f),document:{getElementById:id=>id==='bench'?null:{scrollIntoView:()=>wbTargets.push(id)},querySelector:()=>({scrollIntoView:()=>wbTargets.push('question')})}};vm.createContext(wbRouter);vm.runInContext(wbRoute,wbRouter);wbRouter.route();assert.equal(wbRouter.ed,oldSet);assert.equal(wbRouter.st.current,1);wbTimers.shift()();assert.equal(wbTargets.at(-1),'question');wbRouter.st.submitted=true;wbRouter.route();wbTimers.shift()();assert.equal(wbTargets.at(-1),'sol-2','a kept question in a completed set resolves to its corresponding result block');wbRouter.location.hash='#2026-10-01/q4/solution';wbRouter.route();wbTimers.shift()();assert.equal(wbTargets.at(-1),'sol-2');wbRouter.document.getElementById=id=>id==='bench'?{}:null;wbRouter.location.hash='#bench';const renders=wbRoutes.length;wbRouter.route();assert.equal(wbRoutes.length,renders,'native skip preserves the existing set');wbRouter.document.getElementById=()=>null;wbRouter.route();assert.equal(wbRouter.ed,latestSet,'skip from Ledger still opens the problem set instead of leaving the archive');wbRouter.location.hash='#archive';wbRouter.route();assert.equal(wbRoutes.length,renders+2);
console.log('Field Brief edition/story and Workbook set/question/solution/archive routing; skip links preserve an existing edition and remain usable from Ledger passed.');

// An explicit reading link must never insert/remove recovery UI above its measured target.
const linkedBrief=recoveryContext('/daily-watchlist-5/');linkedBrief.location.hash='#2026-10-01/03';linkedBrief.write(linkedBrief.key(),{edition:'2026-10-01',section:'story-03',offset:300,label:'Story 03'});linkedBrief.update({detail:reset.state});assert(linkedBrief.engaged&&linkedBrief.resume.hidden,'explicit Field Brief story deep links suppress recovery');
const linkedBook=recoveryContext('/daily-econ-challenge/');linkedBook.location.hash='#2026-10-01/q4';linkedBook.update({detail:resetBook.state});assert(linkedBook.engaged&&linkedBook.resume.hidden,'explicit Workbook questions take precedence over recovery');
const linkedJournal=recoveryContext('/weekly-economics-environment/');linkedJournal.document.getElementById=id=>id==='carbon-border'?{closest:()=>({})}:null;linkedJournal.location.hash='#edition-2026-09-25';linkedJournal.write(linkedJournal.key(),{edition:'2026-09-25',section:'article-one',offset:220,label:'Saved entry'});linkedJournal.update({detail:reused.state});assert(!linkedJournal.resume.hidden,'edition-only visits still offer Resume');linkedJournal.explicitNavigation('#carbon-border');assert(linkedJournal.engaged&&linkedJournal.resume.hidden,'existing recovery collapses before article geometry is measured');assert(linkedJournal.readingTarget('#cp-ll-2026-09-25-figure-grid-1'));assert(linkedJournal.readingTarget('#heron-h-2026-09-25-a'));assert(!linkedJournal.readingTarget('#top'));
console.log('Explicit reading deep links preserve target geometry; ordinary edition visits retain the distinct recovery prompt passed.');

// A font-ready story jump must not outlive Start from top or a newer rendered edition.
const storyScroll=fbPage.slice(fbPage.indexOf('    const target=storyNo&&'),fbPage.indexOf('\n  /* ---- day / night:'));
const storyFrames=[],storyFonts=[],storyCalls=[],storyNode={id:'story-03',getBoundingClientRect(){return{}},scrollIntoView:o=>storyCalls.push(o.block)};
const storyContext={storyNo:'03',ed:{date:'2026-10-01'},location:{hash:'#2026-10-01/03'},document:{getElementById:()=>storyNode,fonts:{ready:{then:f=>storyFonts.push(f)}}},requestAnimationFrame:f=>storyFrames.push(f),window:{scrollTo(){}}};vm.createContext(storyContext);vm.runInContext('(function(){'+storyScroll+')()',storyContext);storyContext.location.hash='#2026-10-01';storyFonts.shift()();storyFrames.shift()();assert.equal(storyCalls.length,0,'Start from top cancels a pending story jump');storyContext.location.hash='#2026-10-01/03';vm.runInContext('(function(){'+storyScroll+')()',storyContext);storyFonts.shift()();storyFrames.shift()();assert.deepEqual(storyCalls,['start']);vm.runInContext('(function(){'+storyScroll+')()',storyContext);storyContext.document.getElementById=()=>({id:'story-03'});storyFonts.shift()();storyFrames.shift()();assert.equal(storyCalls.length,1,'a replaced story node cannot receive a stale scroll');
console.log('Font-ready Field Brief story navigation and cancellation by Start from top / replaced edition passed.');
