const fs=require('fs'),vm=require('vm'),assert=require('assert');
const source=fs.readFileSync('weekly-economics-environment/index.html','utf8');
const block=source.slice(source.indexOf('function heronScroll()'),source.indexOf('function initCompanion()'));
function classes(){const s=new Set;return {add:x=>s.add(x),remove:x=>s.delete(x),contains:x=>s.has(x),toggle(x){s.has(x)?s.delete(x):s.add(x)}}}
let now=0,frames=[],timers=[],seen=[],tick=0;
const ctx={innerWidth:1400,innerHeight:900,document:{body:{classList:{contains:()=>false},append(){}},createElement:()=>({style:{},classList:classes(),setAttribute(){}})},performance:{now:()=>now},requestAnimationFrame:f=>(frames.push(f),frames.length),clearTimeout:()=>{},setTimeout:f=>(timers.push(f),timers.length),companionOn:()=>true,motionOK:()=>true,edgePoint:p=>({x:1470,y:p.y}),addTo:(key,id)=>seen.push(id),listKey:()=>[],HERON_POSE:{flight:''},HERON:{items:[],edition:{hidden:false,dataset:{edition:'test'}},busy:false,current:null,flight:0,flown:{},flyer:null}};
vm.createContext(ctx);vm.runInContext(block,ctx);
function item(id){return {a:{id},state:'unseen',inZone:true,slot:{isConnected:true,getBoundingClientRect:()=>({left:1050,top:260})},art:{getBoundingClientRect:()=>({top:100,bottom:1000}),querySelector:()=>({getBoundingClientRect:()=>({right:1000})})},btn:{hidden:true,classList:classes()},panel:{hidden:true}}}
function advance(){now+=1500;const f=frames;frames=[];f.forEach(fn=>fn(now))}
const a=item('a'),b=item('b');ctx.HERON.items=[a,b];ctx.heronTick();timers.shift()();assert.equal(a.state,'arrive');assert(ctx.HERON.busy);const token=ctx.HERON.flight;ctx.heronScroll();ctx.heronTick();assert.equal(ctx.HERON.flight,token,'fast scroll must not interrupt arrival');assert.equal(ctx.HERON.current,a);advance();assert.equal(a.state,'perched');a.panel.hidden=false;ctx.heronTick();assert.equal(ctx.HERON.current,a,'open note blocks next intervention');a.panel.hidden=true;ctx.release(a);assert.equal(a.state,'depart');ctx.heronScroll();assert(ctx.HERON.busy);advance();assert.equal(a.state,'label-only');assert(!a.btn.hidden);timers.shift()();assert.equal(b.state,'arrive');advance();assert.equal(b.state,'perched');ctx.release(b);advance();ctx.summon(a);assert.equal(a.state,'note');assert(!ctx.HERON.busy,'reopen is static');ctx.release(a);advance();assert.equal(seen.length,2);assert.equal(frames.length,0);assert.equal(ctx.HERON.current,null);assert.equal(ctx.HERON.flyer.style.display,'none');
// Static mobile/reduced-motion lifecycle.
ctx.motionOK=()=>false;const c=item('c');ctx.HERON.items=[c];ctx.arrive(c);assert.equal(c.state,'perched');assert(!ctx.HERON.busy);ctx.release(c);assert.equal(c.state,'label-only');assert(!c.btn.hidden);
// One pending open waits for an active departure.
ctx.motionOK=()=>true;const d=item('d');ctx.HERON.items=[c,d];ctx.summon(c);ctx.release(c);let opened=false;d.openPending=true;d.openNote=()=>{opened=true;ctx.summon(d)};advance();assert(opened);assert.equal(ctx.HERON.current,d);assert.equal(d.state,'note');
console.log('Heron lifecycle: arrival, queued triggers, fast scrolling, note blocking, departure, label retention, static reopen, mobile/reduced motion and pending open passed.');

const mobile=fs.readFileSync('personal-updates/mobile/mobile.js','utf8');
const recoveryBlock=mobile.slice(mobile.indexOf('const workbook='),mobile.indexOf("addEventListener('periodicals:edition'"));
function recoveryContext(path){
 const stored=new Map(),els=[{id:'article-one',top:800,height:1200,title:'First substantial article'},{id:'connections',top:2000,height:1000,title:'What connects this week'}].map(e=>({...e,offsetHeight:e.height,getClientRects:()=>[1],getBoundingClientRect(){return {top:this.top-c.scrollY,bottom:this.top+this.height-c.scrollY}},querySelector:()=>({textContent:e.title})}));
 const resume={isConnected:true,hidden:true},c={path,stored,state:null,pending:null,saved:null,timer:null,engaged:false,location:{hash:''},scrollY:0,innerHeight:852,resume,resumeTitle:{},resumeContext:{},prev:{},next:{},clearTimeout(){},requestAnimationFrame:f=>f(),images(){},read:k=>stored.get(k)||null,write:(k,v)=>stored.set(k,v),localStorage:{removeItem:k=>stored.delete(k)},window:{scrollTo:p=>{c.scrollY=p.top}},document:{documentElement:{scrollHeight:3200},body:{classList:{contains:()=>false}},getElementById:id=>els.find(e=>e.id===id),querySelector:()=>null,querySelectorAll:s=>s.includes('.ix-item')?[]:els}};
 vm.createContext(c);vm.runInContext(recoveryBlock,c);return c;
}
const reader=recoveryContext('/weekly-economics-environment/');reader.state={current:'2026-09-25',dates:['2026-09-25'],title:'A resilient economy',hash:d=>'#edition-'+d};reader.scrollY=220;reader.save();assert(!reader.read(reader.key()),'masthead scrolling does not create Resume');reader.scrollY=900;reader.save();let record=reader.read(reader.key());assert.equal(record.section,'article-one');assert.equal(record.offset,220);assert(record.label.includes('First substantial article'));reader.pending=record;reader.scrollY=0;reader.restore();assert.equal(reader.scrollY,900,'semantic section and local offset restore reading position');reader.scrollY=2700;reader.save();assert(!reader.read(reader.key()),'Resume is removed near end');
const brief=recoveryContext('/daily-watchlist-5/');brief.state={current:'2026-09-30',label:'30 September',dates:['2026-09-30'],hash:d=>'#'+d};brief.scrollY=1200;brief.save();assert(brief.read(brief.key()).label.includes('Story article-one')); // story labels are derived from stable story IDs.
const book=recoveryContext('/daily-econ-challenge/');book.state={current:'2026-09-30',dates:['2026-09-30'],progress:{no:3,question:3,answered:2,total:8,submitted:false}};book.save();assert.equal(book.read(book.key()).question,3);assert.equal(book.read(book.key()).label,'No. 003 · Question 4 of 8');let restored;book.state.resume=q=>{restored=q};book.pending=book.read(book.key());book.restore();assert.equal(restored,3);book.state.progress.submitted=true;book.save();assert(!book.read(book.key()),'submitted sets do not offer Resume');
console.log('Resume: masthead threshold, semantic section/offset, near-end suppression, story context, native question recovery and completed-set suppression passed.');

const recovering=recoveryContext('/daily-econ-challenge/');const detail={current:'2026-09-30',dates:['2026-09-30'],hash:d=>'#'+d,progress:{no:3,question:1,answered:1,total:8,submitted:false},recovery:{edition:'2026-09-30',question:1,label:'No. 003 · Question 2 of 8'}};recovering.update({detail});assert(!recovering.resume.hidden);recovering.update({detail:{...detail,progress:{...detail.progress,question:2}}});assert(recovering.resume.hidden);recovering.update({detail:{...detail,progress:{...detail.progress,question:2}}});assert(recovering.resume.hidden,'rendering an active question must not reoffer recovery');console.log('Active-session Resume suppression passed.');

const swipeBlock=mobile.slice(mobile.indexOf('let touch=null;'),mobile.indexOf('function theme()'));
const listeners={},swipes=[];let touchTime=0;
const gesture={state:{},tools:{addEventListener:(n,f)=>{listeners[n]=f}},turn:d=>swipes.push(d),Date:{now:()=>touchTime}};
vm.createContext(gesture);vm.runInContext(swipeBlock,gesture);
function swipe(dx,dy,elapsed){touchTime=0;listeners.touchstart({touches:[{clientX:200,clientY:800}]});touchTime=elapsed;listeners.touchend({changedTouches:[{clientX:200+dx,clientY:800+dy}]})}
swipe(120,5,200);swipe(-120,5,200);swipe(20,2,200);swipe(120,100,200);swipe(120,5,900);listeners.touchstart({touches:[{clientX:0,clientY:0}]});listeners.touchcancel();listeners.touchend({changedTouches:[{clientX:120,clientY:0}]});assert.deepEqual(swipes,[-1,1]);assert.deepEqual(Object.keys(listeners),['touchstart','touchend','touchcancel']);console.log('Control-bar swipe direction, movement/time thresholds, vertical rejection and cancellation passed.');

book.state.progress.submitted=false;book.state.progress.answered=8;book.write(book.key(),{edition:'2026-09-30',question:7});book.save();assert(!book.read(book.key()),'fully answered but unsubmitted sets are also at the end');reader.scrollY=1000;reader.pending={edition:reader.state.current,fromTop:true};reader.restore();assert.equal(reader.scrollY,0);console.log('Start-from-top semantic recovery and fully answered set suppression passed.');
