/* Production Oct. 2→3 artwork regression; current content and all non-artwork surfaces are locked. */
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),{execFileSync}=require('node:child_process'),path=require('node:path'),os=require('node:os');
const base='f6aaa82480bd0118a2f63e2e1c975c4e4dcc346a',read=p=>fs.readFileSync(p,'utf8'),old=p=>execFileSync('git',['show',base+':'+p],{encoding:'utf8'});
const art=require('../daily-watchlist-5/artwork.js'),plates=require('../daily-watchlist-5/artwork-archive.js'),marks=require('../personal-updates/issue-marks.js'),registry=require('../personal-updates/issue-mark-archive.js');
const data=s=>JSON.parse(s.match(/id="briefing-data">([\s\S]*?)<\/script>/)[1]),editions=data(read('daily-watchlist-5/index.html')).editions;
assert.deepEqual(editions,data(old('daily-watchlist-5/index.html')).editions,'All canonical text, sources, numbering, timestamp and editorialSelection must be unchanged');
const originalMarks={module:{exports:{}}};vm.runInNewContext(old('personal-updates/issue-mark-archive.js'),originalMarks);
for(const [id,m]of Object.entries(originalMarks.module.exports))if(id!=='fb:2026-10-03')assert.equal(JSON.stringify(registry[id]),JSON.stringify(m),id+' historical mark changed');
const legacy={};const source=old('daily-watchlist-5/index.html');vm.createContext(legacy);vm.runInContext(source.slice(source.indexOf('  function noiseDefs(id)'),source.indexOf('  function issueNumber(ed)')),legacy);
for(const ed of editions)for(const st of ed.stories)if(ed.date<'2026-10-03'||st.number==='04')assert.equal(art.svg(plates.issues[ed.date][st.number],plates),legacy.art(st.art),ed.date+'/'+st.number+' historical or unaffected plate changed');
const yesterday=registry['fb:2026-10-02'],today=registry['fb:2026-10-03'];
assert.equal(today.version,3);assert.equal(today.composition,'capacity-observation');assert.equal(today.phrase,'Observe, enforce & adapt');assert.notEqual(art.markSignature(today),art.markSignature(yesterday));assert(!/rotate|scale|transform/.test(today.frozen),'No. 008 cannot be a transformed boundary plate');assert(!today.frozen.includes('M96 122H430V458H96Z'),'old dominant boundary geometry survives');
for(const n of ['01','02','03','05']){const m=plates.issues['2026-10-03'][n];assert.equal(m.version,2);assert(!Object.values(plates.issues['2026-10-02']).some(x=>x.signature===m.signature));assert(!Object.values(plates.issues['2026-10-02']).some(x=>art.svg(x,plates)===m.frozen));assert(!/transform=/.test(m.frozen));}
assert.equal(new Set(art.scenes.map(s=>s.geometry)).size,art.scenes.length,'Composition IDs cannot disguise duplicate geometry');assert.equal(new Set(art.issueScenes.map(s=>s.geometry)).size,art.issueScenes.length);
const variants=['labor','heat','trade','finance','research','energy','government','climate','infrastructure'];
for(const subject of variants){let history={},previous=new Set();for(let i=1;i<=12;i++){const date='2028-02-'+String(i).padStart(2,'0'),ed={date,stories:Array.from({length:5},(_,j)=>({number:String(j+1).padStart(2,'0'),title:{labor:'Payroll hiring slows',heat:'Heat exposure',trade:'GPU server smuggling',finance:'Sanctions block financial transfers',research:'Research funding cuts',energy:'Diesel fuel reserve release',government:'Court preserves public grants',climate:'Flood lake drainage',infrastructure:'Compute chip capacity'}[subject],art:'ai',category:subject,editorial:{mechanisms:[subject+'-capacity']}}))};const next=art.edition(ed,history);assert.deepEqual(next,art.edition(ed,history));assert.equal(new Set(Object.values(next).map(x=>x.signature)).size,5);for(const m of Object.values(next)){assert(!previous.has(m.signature),subject+' repeats yesterday');assert.match(m.frozen,/viewBox="0 0 800 640"/);}history[date]=next;previous=new Set(Object.values(next).map(x=>x.signature));}}
const missing={...plates,issues:{...plates.issues}};delete missing.issues['2026-10-02'];assert.throws(()=>art.prepare(editions,missing),/Missing historical/);
const broken=art.edition({...editions.at(-1),date:'2026-10-04'},plates.issues);broken['01']={...broken['02']};assert.throws(()=>art.validateEdition({...editions.at(-1),date:'2026-10-04'},broken,art.recent(plates.issues,'2026-10-04')),/Repeated or invalid/);
const changed=editions.map(ed=>({...ed,stories:ed.stories.map(st=>({...st,title:'Incidental later prose correction'}))}));assert.deepEqual(art.prepare(changed,plates),plates,'Published plates must ignore later metadata changes');
for(const framing of ['Observe, enforce and adapt: research systems and staffing','Enforcement of export controls','Energy risks and heat adaptation','Compute and power infrastructure','Payroll employment adjustment','Evidence from experiments']){const history={},signatures=[];for(let i=1;i<=9;i++){const info={date:'2028-03-'+String(i).padStart(2,'0'),no:i,framing,key:'fb'},m={...info,...art.issueModel(info,history)};assert.deepEqual(art.issueModel(info,history),art.issueModel(info,history));assert.notEqual(m.signature,signatures.at(-1));assert(!/transform|rotate/.test(art.issuePlate(m,['paper','ink','accent','support'])));history['fb:'+m.date]=m;signatures.push(m.signature);}}
// Offline SVG, pinned registry, client update and refresh all select the same full artifact.
const hub=read('personal-updates/index.html'),cover=hub.match(/data-issue-mark="fb"[^>]*>([\s\S]*?)<\/div>/)[1];assert.equal(cover,today.frozen);assert.equal(marks.svg(marks.model({key:'fb',date:'2026-10-03',no:8,framing:'later text'})),cover);
const host={dataset:{},removeAttribute(){},closest:()=>null},browser={window:{FieldBriefArtwork:art,PeriodicalsMarkArchive:registry,document:{querySelector:()=>host}}};vm.runInNewContext(read('personal-updates/issue-marks.js'),browser);browser.window.PeriodicalsIssueMarks.update({key:'fb',date:'2026-10-03',no:8});assert.equal(host.innerHTML,cover);
const strip=s=>s.replace(/<script[^>]*src="(?:\.\.\/daily-watchlist-5\/artwork|artwork(?:-archive)?|issue-mark(?:-archive|s))\.js[^>]*><\/script>\n?/g,'').replace(/data-issue-mark="fb"[^>]*>[\s\S]*?<\/div>/,'data-issue-mark="fb">ART</div>');assert.equal(strip(hub),strip(old('personal-updates/index.html')),'Hub beyond artwork/cache imports changed');
const styles=s=>[...s.matchAll(/<style[^>]*>([\s\S]*?)<\/style>/g)].map(m=>m[1]);assert.deepEqual(styles(read('daily-watchlist-5/index.html')),styles(source),'No accepted CSS may change');
for(const p of ['weekly-economics-environment/index.html','daily-econ-challenge/index.html','personal-updates/commonplace/index.html','personal-updates/commonplace/commonplace.js','personal-updates/handbook/index.html','personal-updates/mobile/mobile.css','personal-updates/mobile/mobile.js','personal-updates/mobile-shelf.js','personal-updates/editorial-memory.js','weekly-economics-environment/field-study.js'])assert.equal(read(p),old(p),p+' frozen surface changed');
assert.equal(execFileSync('git',['diff',base,'--name-only','--','rupert'],{encoding:'utf8'}),'','Atlas changed');
const files=['daily-watchlist-5/index.html','daily-watchlist-5/artwork-archive.js','personal-updates/issue-mark-archive.js','personal-updates/index.html','weekly-economics-environment/index.html'],snap=files.map(read);execFileSync(process.execPath,['scripts/prepare_periodicals.cjs']);assert.deepEqual(files.map(read),snap);execFileSync(process.execPath,['scripts/prepare_periodicals.cjs']);assert.deepEqual(files.map(read),snap,'Preparation not byte-idempotent');
// Exercise the actual publisher against a future issue in an isolated fixture, preserving every pin.
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'periodicals-art-'));
try{for(const p of [...files,'daily-econ-challenge/index.html','scripts/prepare_periodicals.cjs','daily-watchlist-5/artwork.js','personal-updates/issue-marks.js','weekly-economics-environment/field-study.js']){fs.mkdirSync(path.dirname(path.join(dir,p)),{recursive:true});fs.writeFileSync(path.join(dir,p),read(p));}const candidate={...editions.at(-1),date:'2026-10-04',stories:editions.at(-1).stories.map(s=>({...s}))};let html=read('daily-watchlist-5/index.html');html=html.replace(/(id="briefing-data">)[\s\S]*?(<\/script>)/,(_,a,b)=>a+JSON.stringify({editions:[...editions,candidate]})+b);fs.writeFileSync(path.join(dir,'daily-watchlist-5/index.html'),html);execFileSync(process.execPath,['scripts/prepare_periodicals.cjs'],{cwd:dir});const future=require(path.join(dir,'daily-watchlist-5/artwork-archive.js'));for(const [date,pin]of Object.entries(plates.issues))assert.deepEqual(future.issues[date],pin);for(const m of Object.values(future.issues[candidate.date]))assert(!Object.values(plates.issues['2026-10-03']).some(x=>x.signature===m.signature));const first=files.map(p=>fs.readFileSync(path.join(dir,p),'utf8'));execFileSync(process.execPath,['scripts/prepare_periodicals.cjs'],{cwd:dir});assert.deepEqual(files.map(p=>fs.readFileSync(path.join(dir,p),'utf8')),first);}finally{fs.rmSync(dir,{recursive:true,force:true});}
console.log('Artwork diversity: all historical marks/plates and content stable; No. 008 structural repair; 540 repeated-topic plates; 54 repeated-framing marks; pinned artifacts; publisher append-only/idempotence; live/fallback/offline agreement; frozen visuals and Atlas passed.');
