const assert=require('node:assert/strict'),fs=require('node:fs'),cp=require('node:child_process'),vm=require('node:vm');
const root=require('node:path').resolve(__dirname,'..'),read=p=>fs.readFileSync(root+'/'+p,'utf8'),base=p=>cp.execFileSync('git',['show','68490dbc4a62fbbdb813dafb04e1ef7fc45f93e5:'+p],{cwd:root,encoding:'utf8'});
function data(s,id){return JSON.parse(s.match(new RegExp('id="'+id+'">([\\s\\S]*?)</script>'))[1]);}
const current=read('daily-econ-challenge/index.html'),before=base('daily-econ-challenge/index.html'),wb=data(current,'challenge-data'),old=data(before,'challenge-data');
// The authorized learning release adds Assistance to historical questions; all prior fields/bytes remain protected.
const core=current.replace(/^          "assistance":.*\n/gm,'');assert.deepEqual(data(core,'challenge-data').editions.slice(0,3),old.editions);assert(core.includes(before.match(/id="challenge-data">([\s\S]*?)\n  \]\n}/)[1].trim()),'All previous edition data bytes retained apart from the authored Assistance addition');
assert.deepEqual(wb.editions.map(x=>x.no),[1,2,3,4]);const set=wb.editions.at(-1);assert.equal(set.date,'2026-10-01');assert.equal(set.questions.length,8);assert.equal(new Set(set.questions.map(q=>q.id)).size,8);
for(const q of set.questions){assert(['single','multi','tf'].includes(q.kind));assert(q.explanation&&q.concepts.length&&q.refs);assert(q.correct.every(i=>i>=0&&i<q.options.length));if(q.kind==='single')assert.equal(q.correct.length,1);}
assert(Math.abs((.08-.03-.02)/2-.015)<1e-12);assert(Math.abs((32000-30000)/(.6-.2)-5000)<1e-9);assert.equal(40*1.05,42);assert.equal(-20-8,-28);assert.equal(1+39*.1,4.9);
const fb=data(read('daily-watchlist-5/index.html'),'briefing-data'),fbOld=data(base('daily-watchlist-5/index.html'),'briefing-data');assert.deepEqual(fb,fbOld);assert.equal(fb.editions.at(-1).stories.length,5);
const memory=require('../personal-updates/editorial-memory.js');
const candidate={title:'Google frontier model faces AI safety scrutiny',editorial:{domain:'technology',entities:['google'],questions:['scaling-ai']}};
const scored=memory.assess(candidate,fb.editions,'2026-10-02');assert.equal(scored.historyDates.length,6);assert(scored.rawPenalty>0);assert(scored.matches.some(m=>m.shared.entities?.includes('google')));
assert.equal(memory.history([], '2026-10-02').length,0);assert.equal(memory.history(fb.editions.slice(0,1),'2026-10-02').length,1);
const many=Array.from({length:10},(_,i)=>({date:'2026-09-'+String(i+10).padStart(2,'0'),stories:[]}));assert.equal(memory.history(many).length,7);assert.equal(memory.history(many)[0].date,'2026-09-19');
const changed={...candidate,editorial:{...candidate.editorial,materialDevelopment:{reason:'The regulator now issued a binding order.',evidenceUrl:'https://www.ftc.gov/',previousStatus:'voluntary',newStatus:'binding order'}}};assert(memory.assess(changed,fb.editions).override);assert.equal(memory.assess(changed,fb.editions).penalty,0);assert(!memory.assess({...candidate,editorial:{materialDevelopment:{reason:'Another headline'}}},fb.editions).override);
const diverse=['technology','technology','environment','economy','public-policy'].map(domain=>({editorial:{domain}}));assert.deepEqual(memory.review(diverse).warnings,[]);assert(memory.review(Array(5).fill(candidate)).needsEditorialDecision);assert(memory.review(Array(5).fill(candidate),{reason:'Exceptional consequential event',evidenceUrl:'https://example.org/primary'}).exception);
const marks=require('../personal-updates/issue-marks.js'),archive=require('../personal-updates/issue-mark-archive.js');
const legacy={module:{exports:{}}};vm.runInNewContext(base('personal-updates/issue-marks.js'),legacy);const original=legacy.module.exports;
for(const [key,editions] of [['fb',fbOld.editions.filter(e=>e.date<'2026-10-01')],['cp',old.editions]])editions.forEach((e,i)=>{const info={key,date:e.date,no:e.no||i+1,title:e.issueTitle,questions:e.questions,framing:[e.deck,e.signalTitle,...e.signal||[]].join(' ')};assert.equal(marks.svg(marks.model(info)),original.svg(original.model(info)));assert.equal(marks.svg(marks.model({...info,framing:'A later incidental text correction'})),archive[key+':'+e.date].frozen);});
assert.equal(archive['sp:2026-09-25'].seed,1102534134);assert.equal(archive['fb:2026-09-30'].seed,2845269718);
assert.equal(archive['fb:2026-10-01'].subject,'compute-power');assert.notEqual(archive['fb:2026-09-30'].frozen,archive['fb:2026-10-01'].frozen);
const a=marks.model({key:'fb',date:'2027-10-01',no:7,framing:'Frontier AI systems need infrastructure power and oversight.'});const b=marks.model({key:'fb',date:'2027-10-02',no:8,framing:a.framing,previous:a});assert.equal(a.subject,b.subject);assert.notEqual(a.composition,b.composition);assert.notEqual(marks.svg(a).split('<path d="M42')[0],marks.svg(b).split('<path d="M42')[0]);
const ll=read('weekly-economics-environment/index.html'),studies=data(ll,'field-studies'),oldFigure=base('weekly-economics-environment/index.html').match(/<figure class="hero-art">([\s\S]*?)<\/figure>/)[1];assert.equal(studies['2026-09-25'].html,oldFigure);assert.equal(ll.match(/<figure class="hero-art"[^>]*>([\s\S]*?)<\/figure>/)[1],oldFigure);
const field=require('../weekly-economics-environment/field-study.js'),next=field.artifact({date:'2026-10-02',no:2,synthesis:'Water flows and fish displacement alter river exposure',previous:studies['2026-09-25']}),third=field.artifact({date:'2026-10-09',no:3,synthesis:'Water flows and fish displacement alter river exposure',previous:next});assert(next.html.includes('FIELD STUDY 002'));assert(third.html.includes('FIELD STUDY 003'));assert.notEqual(next.composition,third.composition);assert.deepEqual(next,field.artifact({date:'2026-10-02',no:2,synthesis:'Water flows and fish displacement alter river exposure',previous:studies['2026-09-25']}));
assert.match(ll,/<h1>The Price of a<br><em>Resilient Economy<\/em><\/h1>/);assert.match(read('weekly-economics-environment/refinement.css'),/\.hero h1,\.overview-item h3,\.entry h2\{font-family:'LM Roman Dunhill'/);
// Preparation is reproducible; never silently changes pinned illustration bytes.
const paths=['personal-updates/issue-mark-archive.js','personal-updates/index.html','weekly-economics-environment/index.html'],snap=paths.map(read);cp.execFileSync(process.execPath,['scripts/prepare_periodicals.cjs'],{cwd:root});assert.deepEqual(paths.map(read),snap);
console.log('Publication integrity, eight question contracts, preserved archive bytes, seven-edition history, repeat penalty/override, diversity defaults, immutable marks, distinct repeated-subject layouts, original Field Study, sequential/deterministic new studies, title hierarchy and idempotent preparation passed.');
