import assert from 'node:assert/strict';
import {accessProblem} from '../assets/js/core/publication.js';
import {selectCurrentPair,archiveGroups} from '../assets/js/core/editions.js';
import {placeStatuses} from '../assets/js/core/atlas.js';
const edition={id:'2026-W40-tue',status:'published',slot:'tuesday',published_at:'2026-09-29T07:00:00-04:00',weekend:{start:'2026-10-03',end:'2026-10-04'},flagship:{place_id:'trail'}};
const check={place_id:'trail',checked:'2026-09-29',official_url:'https://www.ncparks.gov/trails',status:'open',discrepancy:false};
assert.equal(accessProblem(edition,[check],['www.ncparks.gov']),null);
assert.match(accessProblem(edition,[],['www.ncparks.gov']),/Missing/);
assert.match(accessProblem(edition,[{...check,status:'closed'}],['www.ncparks.gov']),/closed/);
assert.match(accessProblem(edition,[{...check,discrepancy:true}],['www.ncparks.gov']),/disagreement/);
assert.match(accessProblem(edition,[{...check,checked:'2026-09-01'}],['www.ncparks.gov']),/Refresh/);
assert.match(accessProblem(edition,[{...check,official_url:'https://www.alltrails.com/trail'}],['www.ncparks.gov']),/secondary/);
const withdrawn={...edition,status:'withdrawn',place_roles:[{place_id:'trail',role:'flagship'}]};
const manifest={editions:[withdrawn]},now=new Date('2026-09-30T12:00:00-04:00');
assert.equal(selectCurrentPair(manifest,now).tuesday.status,'withdrawn');
assert.equal(archiveGroups(manifest,now)[0].editions[0].status,'withdrawn');
assert.equal(placeStatuses({places:[{id:'trail'}]},manifest,{now}).get('trail').status,'register');
console.log('9 corrective publication and withdrawal assertions passed');
const {replacementFor}=await import('../assets/js/core/publication.js');
const candidate={...edition,id:'2026-W40-r1-tue',flagship:{place_id:'riverwalk'}};
const checked={...check,place_id:'riverwalk',checked:'2026-09-30',official_url:'https://www.hillsboroughnc.gov/riverwalk'};
const stamp='2026-09-30T18:00:00-04:00',hosts=['www.ncparks.gov','www.hillsboroughnc.gov'];
const result=replacementFor(edition,[candidate],[checked],hosts,stamp);
assert.equal(result.withdrawn.status,'withdrawn');assert.equal(edition.status,'published');
assert.equal(result.replacement.id,candidate.id);assert.equal(result.replacement.published_at,stamp);
const rejected=replacementFor(edition,[{...candidate,flagship:{place_id:'closed'}},candidate],[checked,{...checked,place_id:'closed',status:'closed'}],hosts,stamp);
assert.equal(rejected.replacement.id,candidate.id);assert.equal(rejected.rejected.length,1);
assert.equal(replacementFor(edition,[candidate],[{...checked,official_url:'https://www.alltrails.com/trail'}],hosts,stamp).replacement,null);
assert.equal(replacementFor(edition,[candidate],[{...checked,checked:'2026-09-01'}],hosts,stamp).replacement,null);
assert.equal(replacementFor(edition,[candidate],[{...checked,checked:'2026-10-03'}],hosts,stamp).replacement,null);
const originalManifest={...withdrawn,published_at:edition.published_at};
const revisedManifest={...candidate,status:'published',published_at:stamp};
const revisions={editions:[originalManifest,revisedManifest]};
assert.equal(selectCurrentPair(revisions,new Date('2026-09-30T19:00:00-04:00')).tuesday.id,candidate.id);
assert.equal(archiveGroups(revisions,new Date('2026-09-30T19:00:00-04:00'))[0].editions.length,2);
assert.equal(selectCurrentPair(revisions,new Date('2026-09-30T17:00:00-04:00')).tuesday.status,'withdrawn');
console.log('12 replacement lifecycle assertions passed');
