import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {durationLabel,routeFamilies,wholeJourneyBounds,opportunityZones,overnightZones,journeyLegs,journeySchedule,routeProgress,distinctRoute} from '../assets/js/core/journey.js';
import {cleanPlan,readBackup} from '../assets/js/core/travel.js';
import {weatherParts} from '../assets/js/core/weather.js';
import {discoveryQuery,activityFromOSM,discoverActivities,ACTIVITY_TYPES} from '../assets/js/core/discovery.js';
import {drivingAlternatives} from '../assets/js/core/routing.js';
import {routeBounds} from '../assets/js/core/trip-map.js';
import {renderAtlas,renderTravel,renderArchive,chrome} from '../assets/js/core/render.js';
let checks=0;const check=(fn)=>{fn();checks++;};
const route=(coordinates,minutes=180,miles='180')=>({feature:{type:'Feature',properties:{mode:'drive'},geometry:{type:'LineString',coordinates}},minutes,miles});
const origin={label:'A',lat:35,lng:-79},destination={label:'B',lat:47,lng:-122};
const base=route([[-79,35],[-89,38],[-100,40],[-112,44],[-122,47]],3030,'2800');
for(const [input,expected]of [[0,'0 min'],[42,'42 min'],[60,'1 h'],[61,'1 h 1 min'],[90,'1 h 30 min'],[120,'2 h'],[3029,'50 h 29 min'],[null,'Unavailable']])check(()=>assert.equal(durationLabel(input),expected));
check(()=>assert.equal(routeFamilies(Array(12).fill(base)).length,1));
const near=route(base.feature.geometry.coordinates.map(([x,y])=>[x,y+.005]),3033,'2802');check(()=>assert.equal(distinctRoute(near,base),false));
const far=route([[-79,35],[-87,43],[-100,47],[-111,49],[-122,47]],3200,'2950');check(()=>assert.equal(routeFamilies([far,base,near]).length,2));
const extras=Array.from({length:10},(_,i)=>route([[-79,35],[-100,49+i],[-122,47]],3200+i*30,'3000'));check(()=>assert.ok(routeFamilies([base,...extras]).length<=3));
check(()=>assert.equal(routeFamilies([far,base])[0].minutes,3030));
check(()=>assert.deepEqual(wholeJourneyBounds([base],origin,destination),[[-122.01,34.99],[-78.99,47.01]]));
check(()=>assert.equal(opportunityZones(base).length,8));
check(()=>assert.ok(overnightZones(base).length>=5&&overnightZones(base).length<=8));
check(()=>assert.equal(overnightZones(route([[-79,35],[-78,36]],120,'100')).length,0));
check(()=>assert.ok(routeProgress({lat:40,lng:-100},base)>.3));
const stop={id:'town',name:'Nashville',location:{label:'Nashville',lat:36,lng:-87},minutes:45,category:'town',categoryLabel:'Town walk',dog:'Unverified',why:'A selected town.',links:[]};
const legs=journeyLegs(origin,destination,[stop]);check(()=>assert.equal(legs.length,2));check(()=>assert.equal(legs[0].to.label,'Nashville'));check(()=>assert.equal(legs[1].from.label,'Nashville'));
check(()=>assert.equal(journeyLegs(origin,destination).length,1));
const other={...stop,id:'other',name:'Other town',location:{label:'Other town',lat:40,lng:-100}};
check(()=>assert.equal(journeyLegs(origin,destination,[other,stop])[0].to.label,'Other town'));
const timings=journeySchedule(legs,[{minutes:450},{minutes:450}],{start:'2026-10-03',departure:'09:00',stops:[{...stop,overnight:true}]});check(()=>assert.equal(timings.rows[0].arrival,'2026-10-03 · 16:30'));check(()=>assert.equal(timings.rows[0].nextDeparture,'2026-10-04 · 09:00'));check(()=>assert.equal(timings.rows[1].arrival,'2026-10-04 · 16:30'));
const late=journeySchedule(legs,[{minutes:850},{minutes:60}],{departure:'09:00',stops:[{...stop,overnight:true}]});check(()=>assert.equal(late.rows[0].nextDeparture,'Day 2 · 09:10'));
const plan=cleanPlan({id:'tp_finish',title:'Test journey',legs,journey:{origin,destination,family:base,families:[base],routes:[base,base],stops:[stop],destinationActivities:[{...other,minutes:30}]},planning:{departure:'08:30',detour:20}});check(()=>assert.deepEqual(readBackup(JSON.stringify({schema_version:1,plans:[plan]}))[0],plan));
const manual=cleanPlan({id:'tp_manual',title:'Manual journey',legs:[{mode:'air',from:origin,to:destination,minutes:300}],manual_routes:[base]});
check(()=>assert.deepEqual(readBackup(JSON.stringify({schema_version:1,plans:[manual]}))[0],manual));
check(()=>assert.equal(manual.manual_routes[0].feature.properties.mode,'air'));
check(()=>assert.equal(journeySchedule(manual.legs,manual.manual_routes).driveMinutes,0));
check(()=>assert.throws(()=>cleanPlan({...manual,manual_routes:[]}),/do not match/));
check(()=>assert.throws(()=>cleanPlan({...manual,manual_routes:[{...base,feature:{geometry:{type:'LineString',coordinates:[[Infinity,3],[2,3]]}}}]}),/Invalid saved route/));
const huge={...base.feature,geometry:{type:'LineString',coordinates:Array.from({length:150000},(_,i)=>[-122+43*i/149999,35+12*i/149999])}};
check(()=>assert.deepEqual(routeBounds([huge]),[[-122.01,34.99],[-78.99,47.01]]));
const markerOutside={label:'An activity preview',lng:170,lat:-40};
check(()=>assert.ok(wholeJourneyBounds([base],origin,destination)[1][0]<markerOutside.lng));
check(()=>assert.throws(()=>cleanPlan({...plan,journey:{...plan.journey,stops:[stop,stop]}}),/Duplicate/));
check(()=>assert.throws(()=>cleanPlan({...plan,journey:{...plan.journey,family:{...base,feature:{geometry:{type:'LineString',coordinates:[[Infinity,3],[2,3]]}}}}}),/Invalid saved route/));
const weather=weatherParts({flagship:{headline_condition:'Fine in light rain; Sun 40% showers'},conditions:{summary:'Saturday partly sunny, high near 78, 30% chance of showers. Sunday mostly cloudy, high near 75, 40%.'}});check(()=>assert.equal(weather.days.length,2));check(()=>assert.equal(weather.trail,'Fine in light rain'));check(()=>assert.ok(!JSON.stringify(weather).includes('80')));
check(()=>assert.equal(weather.days[1].forecast,'mostly cloudy · high near 75 · 40% showers'));
check(()=>assert.deepEqual(weatherParts({conditions:{days:[{day:'Saturday',forecast:'Sunny'},{day:'Sunday',forecast:'Cloudy'}],trail_note:'Leash required'}}).days,[{day:'Saturday',forecast:'Sunny'},{day:'Sunday',forecast:'Cloudy'}]));
const warning=weatherParts({flagship:{condition_level:'adverse',headline_condition:'Saturday showers 50%; Sunday showers 70%'},conditions:{summary:'Saturday high near 75. Sunday 70% showers. Saturday morning is provisional.'}});check(()=>assert.equal(warning.days.length,2));check(()=>assert.match(warning.trail,/provisional/));check(()=>assert.equal(warning.adverse,true));
const query=discoveryQuery(origin);for(const key of ['ice_cream','bakery','restaurant','biergarten','marketplace','garden_centre','outdoor','university','beach','viewpoint','ferry_terminal','footway','pier'])check(()=>assert.ok(query.includes(key)));
check(()=>assert.ok(ACTIVITY_TYPES.length>=15));
const sample={type:'node',id:1,lat:35,lon:-79,tags:{name:'Patio',amenity:'restaurant',outdoor_seating:'yes'}};
check(()=>assert.match(activityFromOSM(sample).dog,/unverified/));check(()=>assert.equal(activityFromOSM({...sample,tags:{...sample.tags,dog:'no'}}),null));check(()=>assert.equal(activityFromOSM({...sample,tags:{...sample.tags,access:'private'}}),null));
check(()=>assert.match(activityFromOSM({...sample,tags:{...sample.tags,dog:'yes'}}).dog,/OpenStreetMap/));
const result=await discoverActivities(origin,{request:async(url,options)=>{assert.equal(options.referrerPolicy,'origin');assert.equal(options.method,'POST');return {ok:true,json:async()=>({elements:[sample,sample]})};}});check(()=>assert.equal(result.length,1));
check(()=>assert.ok(query.includes('[name]->.near;')));
const alternatives=await drivingAlternatives(origin,{lat:36,lng:-78},{request:async url=>{assert.ok(String(url).includes('alternatives=true'));return {ok:true,json:async()=>({code:'Ok',routes:[{geometry:{type:'LineString',coordinates:[[-79,35],[-78,36]]},duration:3600,distance:16093.44,legs:[{steps:[{ref:'I-40',distance:15000}]}]}]})};}});check(()=>assert.equal(alternatives[0].corridor,'I-40'));
const model={statuses:new Map(),groups:[],counts:{all:0},features:[],bounds:null};const atlas=renderAtlas(model,{base:'../'});
check(()=>assert.ok(!atlas.split('class="frame-options"')[1].split('</div></details>')[0].includes('id="recenter"')));
check(()=>assert.match(atlas,/map-direct-controls.*id="recenter".*id="relief"/));check(()=>assert.match(atlas,/<small id="atlas-context" hidden><\/small>/));check(()=>assert.ok(!atlas.includes('North Carolina · Place Directory')));
const travel=renderTravel({places:{places:[],reference_points:{}},history:[]});check(()=>assert.ok(travel.indexOf('id="trip-origin"')<travel.indexOf('id="trip-legs"')));check(()=>assert.ok(travel.indexOf('id="build-stage"')<travel.indexOf('Trip Table')));check(()=>assert.ok(!travel.includes('Break every')));
check(()=>assert.match(renderArchive([],{base:'../'}),/archive-layout.*archive-rail.*archive-index/));check(()=>assert.match(chrome({base:'../',active:'atlas',weekLabel:'Week 40',body:''}),/footer-identity.*rupert-outline\.svg/));
const css=readFileSync(new URL('../assets/css/atlas.css',import.meta.url),'utf8');check(()=>assert.match(css,/grid-auto-flow:column;grid-auto-columns:minmax\(280px/));check(()=>assert.match(css,/--f-secondary:"Latin Modern Roman Dunhill"/));
const log=readFileSync(new URL('../assets/js/field-log-view.js',import.meta.url),'utf8');check(()=>assert.match(log,/head-note dog-only/));check(()=>assert.ok(!log.includes('log-header-count')));
const menus=readFileSync(new URL('../assets/js/core/menus.js',import.meta.url),'utf8');check(()=>assert.match(menus,/pointerleave/));check(()=>assert.match(menus,/focused\(\)/));check(()=>assert.match(menus,/e\.key!=='Escape'/));
const provider=readFileSync(new URL('../assets/js/map/maplibre-provider.js',import.meta.url),'utf8');check(()=>assert.ok(/minZoom:\s*travel\s*\?\s*2\s*:\s*5/.test(provider)));
const manifest=JSON.parse(readFileSync(new URL('../manifest.webmanifest',import.meta.url)));check(()=>assert.equal(manifest.scope,'/rupert/'));check(()=>assert.equal(manifest.display,'standalone'));check(()=>assert.equal(manifest.theme_color,'#1D2A3A'));
for(const icon of manifest.icons)check(()=>assert.ok(readFileSync(new URL('../'+icon.src,import.meta.url)).length>500));
console.log(`${checks} final-build regression checks passed.`);
