import assert from 'node:assert/strict';
import {frameFeatures,frameMap} from '../assets/js/core/framing.js';
const features=[['a','recommended',[-79,36]],['b','recommended',[-78,35]],['old','withdrawn',[-80,37]]].map(([id,status,coordinates])=>({type:'Feature',geometry:{type:'Point',coordinates},properties:{id,status}}));
const regions=[{label:'North',ids:['a','old']},{label:'South',ids:['b']}];
const original=JSON.stringify({features,regions});let fits=[];
const map={fit:(bounds,options)=>fits.push({bounds,options}),setMarkers:()=>{throw Error('Framing must not filter markers');},select:()=>{throw Error('Framing must not change selection');}};
assert.deepEqual(frameFeatures(features,regions,'all'),features);
assert.deepEqual(frameFeatures(features,regions,'recommended').map(f=>f.properties.id),['a','b']);
assert.deepEqual(frameFeatures(features,regions,'withdrawn').map(f=>f.properties.id),['old']);
assert.deepEqual(frameFeatures(features,regions,'region:0').map(f=>f.properties.id),['a','old']);
assert.equal(frameMap(map,features,regions,'all'),true);
assert.deepEqual(fits.at(-1).bounds,[[-80,35],[-78,37]]);
assert.equal(frameMap(map,features,regions,'region:1'),true);
assert.deepEqual(fits.at(-1),{bounds:[[-78,35],[-78,35]],options:{maxZoom:13}});
assert.equal(frameMap(map,features,regions,'withdrawn'),true);
assert.equal(frameMap(map,features,regions,'region:99'),false);
assert.equal(frameMap(null,features,regions,'all'),false);
assert.equal(frameMap(map,[],regions,'all'),false);
assert.equal(fits.length,3);
assert.equal(JSON.stringify({features,regions}),original);
console.log('14 camera framing checks passed (markers and selection preserved).');
