import assert from 'node:assert/strict';
import {reuseEligibility,rankCandidates,experienceKey} from '../assets/js/core/recommendations.js';
import {placeStatuses,registerGroups,markerFeatures,counts} from '../assets/js/core/atlas.js';
import {renderEdition,renderWeek} from '../assets/js/core/render.js';
import {accessProblem} from '../assets/js/core/publication.js';
const start='2026-01-01T12:00:00Z', all=['spring','summer','autumn','winter'];
const old={id:'old',status:'published',published_at:start,slot:'tuesday',weekend:{start:'2026-01-03',end:'2026-01-04'},flagship:{place_id:'park',title:'Old walk',seasons:all,experiences:['woodland'],snapshot:{route:{route_id:'loop@1'}}},place_roles:[{place_id:'park',role:'flagship'}]};
const candidate={...old,id:'new',flagship:{...old.flagship,title:'Cosmetic rewrite'}};
const at=days=>new Date(+new Date(start)+days*86400000).toISOString();
assert.equal(reuseEligibility(candidate,[old],{at:at(179.99)}).eligible,false);
assert.equal(reuseEligibility(candidate,[old],{at:at(180)}).eligible,true);
assert.equal(reuseEligibility(candidate,[old],{at:at(364),log:[{edition:'old',history_kind:'completed',date:'2026-01-03'}]}).eligible,false);
assert.equal(reuseEligibility(candidate,[old],{at:at(365),log:[{edition:'old',history_kind:'completed',date:'2026-01-03'}]}).eligible,true);
const different={...candidate,flagship:{...candidate.flagship,experience_id:'sunset-picnic',difference_note:'A sunset picnic at the water instead of the woodland loop.',experiences:['picnic']}};
assert.equal(reuseEligibility(different,[old],{at:at(119)}).eligible,false);
assert.equal(reuseEligibility(different,[old],{at:at(120)}).eligible,true);
assert.equal(reuseEligibility({...different,flagship:{...different.flagship,difference_note:''}},[old],{at:at(120)}).eligible,false);
assert.equal(experienceKey({...candidate,flagship:{...candidate.flagship,snapshot:{route:{route_id:'loop@2'}}}}),experienceKey(old));
assert.equal(reuseEligibility({...candidate,weekend:{start:'2026-07-04'},flagship:{...candidate.flagship,seasons:['winter']}},[old],{at:at(200)}).eligible,false);
assert.equal(reuseEligibility({...candidate,flagship:{...candidate.flagship,event_window:{start:'2026-10-01',end:'2026-10-03'}}},[old],{at:at(200)}).eligible,false);
assert.equal(reuseEligibility({...candidate,flagship:{...candidate.flagship,experiences:['event']}},[],{at:at(200)}).eligible,false);
assert.equal(reuseEligibility({...candidate,weekend:{start:'2026-07-04'},flagship:{...candidate.flagship,seasons:['winter']}},[],{at:at(200)}).eligible,false);
assert.equal(reuseEligibility({...candidate,flagship:{...candidate.flagship,experiences:['event'],event_window:{start:'2026-01-04',end:'2026-01-04'}}},[],{at:start}).eligible,true);
assert.equal(reuseEligibility({...candidate,flagship:{...candidate.flagship,experiences:['event'],event_window:{start:'2026-01-02',end:'2026-01-02'}}},[],{at:start}).eligible,false);
const repeat={...old,id:'second',published_at:at(180)};
assert.equal(reuseEligibility(candidate,[old,repeat],{at:at(359)}).eligible,false);
assert.equal(reuseEligibility(candidate,[old,repeat],{at:at(360)}).eligible,true);
assert.equal(reuseEligibility(candidate,[old,repeat],{at:at(360),log:[{edition:'old',history_kind:'completed',date:'2026-01-03'}]}).eligible,false);
assert.equal(reuseEligibility(candidate,[old],{at:at(1)}).recencyPenalty > 99,true);
assert.equal(reuseEligibility(candidate,[old],{at:at(360)}).recencyPenalty,0);
const unseen={...candidate,id:'cafe',flagship:{...candidate.flagship,place_id:'cafe',experiences:['cafe']}};
assert.equal(rankCandidates([candidate,unseen],[old],{at:at(360)})[0].candidate.id,'cafe');
assert.equal(rankCandidates([candidate,unseen],[old],{at:at(360)})[0].diversity,15);
const stronger={...candidate,suitability_score:100};
assert.equal(rankCandidates([stronger,{...unseen,suitability_score:10}],[old],{at:at(360)})[0].candidate.id,'new');
const places={places:[{id:'park',name:'Park',region:'NC',access:{lat:36,lng:-79}},{id:'seed',name:'Seed',region:'NC',access:{lat:35,lng:-78}}]};
const manifest={editions:[old,{...old,id:'future',place_roles:[{place_id:'seed',role:'flagship'}],published_at:at(600)}]};
const now=new Date(at(200));
const states=placeStatuses(places,manifest,{now,log:[{place_id:'seed'}]});
assert.deepEqual([...states.keys()],['park']);
assert.deepEqual([...placeStatuses(places,{editions:[{...old,place_roles:[{place_id:'seed',role:'wildcard'}]}]},{now}).keys()],[]);
assert.equal(markerFeatures(places,states).length,1);
assert.equal(registerGroups(places,states)[0].places.length,1);
assert.equal(counts(states).all,1);
const withdrawn=placeStatuses(places,{editions:[{...old,status:'withdrawn'}]},{now});
assert.equal(withdrawn.get('park').status,'withdrawn');assert.equal(withdrawn.get('park').editions[0].status,'withdrawn');
assert.equal(placeStatuses(places,{editions:[old,{...repeat,status:'withdrawn'}]},{now}).get('park').status,'withdrawn');
const editions=structuredClone(candidate);editions.published_at=at(360);editions.flagship.snapshot.access={};editions.flagship.snapshot.as_of="2026-01-01";editions.conditions={as_of:at(350)};editions.practical={};
const html=renderEdition(editions,{base:'../../',places,photos:{photos:[]},history:[old],now});
assert.match(html,/Previously suggested/);assert.match(html,/edition\/old\//);
const week=renderWeek({weekend:old.weekend,tuesday:{id:editions.id},thursday:null,state:'upcoming',missing:{thursday:at(5)}},{[editions.id]:editions},{base:'',places,photos:{photos:[]}});
assert.match(week,/Tuesday edition/);assert.doesNotMatch(week,/Published Wed/);
const revised=structuredClone(editions);revised.published_at='2026-09-30T16:00:00-04:00';
const revisedHtml=renderEdition(revised,{base:'../../',places,photos:{photos:[]},history:[old],now});
assert.match(revisedHtml,/<time datetime="2026-09-30T16:00:00-04:00">Tuesday edition · 30 Sep<\/time>/);
assert.doesNotMatch(revisedHtml,/Tuesday edition · Wed/);
const official={place_id:'park',status:'open',checked:'2026-01-01',official_url:'https://www.ncparks.gov/park'};
const fresh={...official,checked:'2026-06-30'};
assert.equal(accessProblem(old,[fresh,official],['www.ncparks.gov']),null);
assert.equal(accessProblem({...candidate,published_at:at(180)},[official,fresh],['www.ncparks.gov']),null);
assert.match(accessProblem({...candidate,published_at:at(180)},[official,{...fresh,status:'closed'}],['www.ncparks.gov']),/closed/);
assert.match(accessProblem({...candidate,published_at:at(180)},[fresh,{...fresh,status:'closed'}],['www.ncparks.gov']),/closed/);
console.log('40 publication history, cooldown, category variety and provenance assertions passed');
