import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { trafficConfig } from '../assets/js/traffic-config.js';
import { trafficAvailable, congestionLevel, parseTrafficRoute, trafficRoute, trafficProviderLabel, TRAFFIC_FRESH_MS, TRAFFIC_COLORS } from '../assets/js/core/traffic.js';
import { atlasStyle } from '../assets/js/map/style.js';
let checks=0;const check=fn=>{fn();checks++;};
const config={provider:'mapbox',publicToken:'pk.unit.fixture',allowedOrigins:['https://atlas.example']};
check(()=>assert.equal(trafficAvailable(trafficConfig,'https://iainholmes.github.io'),!!trafficConfig.publicToken));
check(()=>assert.equal(trafficAvailable(config,'https://atlas.example'),true));
for(const token of ['', 'secret', 'sk'+'.unit.fixture'])check(()=>assert.equal(trafficAvailable({...config,publicToken:token},'https://atlas.example'),false));
check(()=>assert.equal(trafficAvailable(config,'https://other.example'),false));
for(const [n,level] of [[0,'normal'],[1,'mild'],[39,'mild'],[40,'moderate'],[59,'moderate'],[60,'heavy'],[79,'heavy'],[80,'severe'],[100,'severe'],[null,'unknown'],[NaN,'unknown'],[-1,'unknown'],[101,'unknown']])check(()=>assert.equal(congestionLevel(n),level));
check(()=>assert.equal(congestionLevel(undefined,'low'),'normal'));
check(()=>assert.equal(congestionLevel(null,'low'),'unknown'));
const coordinates=Array.from({length:9},(_,i)=>[-79+i/100,35+i/100]);
const fixture={code:'Ok',routes:[{duration:2580,duration_typical:2160,distance:43612,geometry:{type:'LineString',coordinates},legs:[{annotation:{congestion_numeric:[0,0,12,45,65,85,null,0]},closures:[{geometry_index_start:7,geometry_index_end:8}],incidents:[{type:'construction',description:'Work on selected route',geometry_index_start:3,geometry_index_end:4}]}]}]};
const route=parseTrafficRoute(fixture,100);
check(()=>assert.equal(route.minutes,43));check(()=>assert.equal(route.miles,'27.1'));check(()=>assert.equal(route.fetchedAt,100));
check(()=>assert.equal(trafficProviderLabel(route),'Live Traffic · +7 min vs typical'));
check(()=>assert.deepEqual(route.features.map(f=>f.properties.traffic),['normal','mild','moderate','heavy','severe','unknown','closure']));
check(()=>assert.equal(route.features[0].geometry.coordinates.length,3));
check(()=>assert.deepEqual(route.features.flatMap((f,i)=>i?f.geometry.coordinates.slice(1):f.geometry.coordinates),coordinates));
check(()=>assert.equal(route.unknownSegments,1));check(()=>assert.equal(route.incidents[0].description,'Work on selected route'));
check(()=>assert.equal(trafficProviderLabel({...route,typicalSeconds:null}),'Live Traffic'));
check(()=>assert.equal(trafficProviderLabel({...route,typicalSeconds:route.seconds}),'Live Traffic · Typical travel time'));
check(()=>assert.equal(trafficProviderLabel({...route,typicalSeconds:route.seconds+180}),'Live Traffic · -3 min vs typical'));
const unknown=structuredClone(fixture);delete unknown.routes[0].legs[0].annotation;
check(()=>assert.equal(parseTrafficRoute(unknown).features[0].properties.traffic,'unknown'));
for(const mutate of [d=>d.code='NoRoute',d=>d.routes[0].duration=NaN,d=>d.routes[0].distance=-1,d=>d.routes[0].geometry.coordinates[1]=[181,35],d=>d.routes[0].legs.push({}),d=>d.routes[0].legs[0].annotation.congestion_numeric.pop(),d=>d.routes[0].legs[0].closures[0].geometry_index_end=900]){
 const bad=structuredClone(fixture);mutate(bad);check(()=>assert.throws(()=>parseTrafficRoute(bad),/Live traffic/));
}
const closed=structuredClone(fixture);closed.routes[0].legs[0].incidents[0].closed=true;
check(()=>assert.equal(parseTrafficRoute(closed).features[2].properties.traffic,'closure'));
let requestCount=0;
const result=await trafficRoute({lng:-79,lat:35},{lng:-78,lat:36},{config,origin:'https://atlas.example',now:()=>300,request:async(url,opts)=>{
 requestCount++;const u=new URL(url);
 check(()=>assert.equal(u.origin,'https://api.mapbox.com'));check(()=>assert.match(u.pathname,/driving-traffic\/-79,35;-78,36$/));
 check(()=>assert.equal(u.searchParams.get('annotations'),'congestion,congestion_numeric,closure'));
 check(()=>assert.equal(u.searchParams.get('depart_at'),'now'));check(()=>assert.equal(opts.referrerPolicy,'origin'));
 check(()=>assert.equal(opts.credentials,'omit'));check(()=>assert.equal(opts.cache,'no-store'));
 check(()=>assert.equal(u.searchParams.has('waypoint_names'),false));return {ok:true,json:async()=>fixture};
}});
check(()=>assert.equal(result.fetchedAt,300));check(()=>assert.equal(requestCount,1));
await assert.rejects(()=>trafficRoute({lat:NaN,lng:-79},{lat:36,lng:-78},{config,origin:'https://atlas.example',request:()=>{throw Error('Invalid Home reached service');}}),/Check both/);checks++;
await assert.rejects(()=>trafficRoute({lat:35,lng:-79},{lat:36,lng:-78},{config:{...trafficConfig,publicToken:''},origin:'https://iainholmes.github.io',request:()=>{throw Error('Unconfigured service was called');}}),/not configured/);checks++;
await assert.rejects(()=>trafficRoute({lat:35,lng:-79},{lat:36,lng:-78},{config,origin:'https://atlas.example',request:async()=>({ok:false})}),/temporarily unavailable/);checks++;
check(()=>assert.equal(TRAFFIC_FRESH_MS,300000));
check(()=>assert.equal(atlasStyle('light').layers[0].paint['background-color'],'#E6EAE1'));
check(()=>assert.equal(atlasStyle('traffic').layers[0].paint['background-color'],'#1D2A3A'));
check(()=>assert.equal(atlasStyle('traffic').sources.omt.url,atlasStyle('light').sources.omt.url));
check(()=>assert.equal(atlasStyle('light').layers.some(l=>l.id==='traffic-road-name'),false));
check(()=>assert.equal(atlasStyle('traffic').layers.some(l=>l.id==='traffic-road-name'),true));
check(()=>assert.notEqual(TRAFFIC_COLORS.unknown,TRAFFIC_COLORS.normal));
check(()=>assert.ok(!readFileSync(new URL('../assets/js/traffic-config.js',import.meta.url),'utf8').includes('sk'+'.')));
console.log(`${checks} live-traffic adapter/security assertions PASS (synthetic fixtures, no live credential).`);
